org: edsonguardamino
service: api-registro

provider:
  name: aws
  runtime: python3.12
  iam:
    role: arn:aws:iam::051476014162:role/LabRole

functions:
  crear:
    handler: CrearEstudiante.lambda_handler
    events:
      - http:
          path: /registro/crear
          method: post
          cors: true
          integration: lambda
  login:
    handler: LoginEstudiante.lambda_handler
    events:
      - http:
          path: /registro/login
          method: post
          cors: true
          integration: lambda
  search:
    handler: SearchEstudiante.lambda_handler
    events:
      - http:
          path: /registro/estudiante/search
          method: post
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.json('$')
                }
  searchbycode:
    handler: BuscarEstudiantePorCodigo.lambda_handler
    events:
      - http:
          path: /registro/estudiante/searchbycode
          method: post
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.json('$')
                }


resources:
  Resources:
    TablaEstudiantes:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tabla_estudiantes
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: c_estudiante
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: c_estudiante
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
